### ISSUE TITLE
KC705 and 0.6

### ISSUE THREAD

**Issue by nasahlpa** [lowRISC/lowrisc-fpga#8]
Hi,
I am currently trying to make lowrisc 0.6 working on the KC705 dev board. As the periphery is different and I don't need it, I disabled some periphery parts in my design.

As I get timing constraint errors, I increased the period from 5.000 to 10.000 (like for the nexys4_ddr board) . I also enabled UIExtraClocks as this clock is used to generate the clk signal for the RocketCore.

Synthesis is now fine, ui_addn_clk_0 of dram_ctl is now connected with signal clk (when UIExtraClocks=0, which is suggested by mig_config.prj in kc705_mii branch, then ui_addn_clk_0 isn't available and therefore synthesis fails). However, now I get errors when building the system at step route_design:

`ERROR: [DRC PDRC-34] MMCM_adv_ClkFrequency_div_no_dclk: The computed value 400.000 MHz (CLKIN1_PERIOD, net pll_clk3) for the VCO operating frequency of the MMCME2_ADV site MMCME2_ADV_X1Y1 (cell dram_ctl/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_ui_extra_clocks.mmcm_i) falls outside the operating range of the MMCM VCO frequency for this device (600.000 - 1440.000 MHz). The computed value is (CLKFBOUT_MULT_F * 1000 / (CLKINx_PERIOD * DIVCLK_DIVIDE)). Please run update_timing to update the MMCM settings. If that does not work, adjust either the input period CLKINx_PERIOD (10.000000), multiplication factor CLKFBOUT_MULT_F (4.000000) or the division factor DIVCLK_DIVIDE (1), in order to achieve a VCO frequency within the rated operating range for this device.`
And the corresponding critical warning:
```
[DRC AVAL-46] v7v8_mmcm_fvco_rule1: The current computed target frequency, FVCO, is out of range for cell dram_ctl/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_ui_extra_clocks.mmcm_i. The computed FVCO is 400.000 MHz. The valid FVCO range for speed grade -2 is 600MHz to 1440MHz. The cell attribute values used to compute FVCO are CLKFBOUT_MULT_F = 4.000, CLKIN1_PERIOD = 10.00000, and DIVCLK_DIVIDE = 1 (FVCO = 1000 * CLKFBOUT_MULT_F/(CLKIN1_PERIOD * DIVCLK_DIVIDE)).
This violation may be corrected by:
  1. The timer uses timing constraints for clock period or clock frequency that affect CLKIN1 to set cell attribute CLKIN1_PERIOD, over-riding any previous value. This may already be in place and, if so this violation will be resolved once Timing is run.  Otherwise, consider modifying timing constraints to adjust the CLKIN1_PERIOD and bring FVCO into the allowed range.
  2. In the absence of timing constraints that affect CLKIN1, consider modifying the cell CLKIN1_PERIOD to bring FVCO into the allowed range.
  3. If CLKIN1_PERIOD is satisfactory, modify the CLKFBOUT_MULT_F or DIVCLK_DIVIDE cell attributes to bring FVCO into the allowed range.
  4. The MMCM configuration may be dynamically modified by use of DRP which is recognized by an ACTIVE signal on DCLK pin.
```
What does this mean? I guess the 800MHz clock is taken and divided by 16 (MMCMClkOut0 value) to generate the 50MHz clk for the RocketCore. This is output ui_addn_clk_0 and is connected with clk.

CLKIN1_PERIOD is now 10.000, meaning 100MHz. Before it was 5.000 -> 200MHz. Do I have to change parameter InputClkFreq from 200 to 100? With the formula FVCO=... from above I get 400MHz, which is not a valid value. To change it to something between 600 and 1440MHz I would need to change CLKIN1_PERIOD (which is not working, because 5.000 instead of 10.000 gives me timing errors) or to manipulate  CLKFBOUT_MULT_F. This parameter is also needed by other clocks inside the mig_7 stuff. Therefore, I don't thing I am allowed to change it to a other value.

Can somebody helps me?

**Comment by jrrk** [comment]
Have you tried building kc705_mii branch first? This would be a better starting 
point for any modifications.

In general you cannot transpose timing constraints between boards because the 
master clock crystals will usually be different.

This project is unfinished partly because it is difficult to adjust for the 
frequency of the PHY which has an external clock which is

a nuisance.
